import React, { useState } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity, Modal,
} from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { SafeScreen } from '../../src/components/layout/SafeScreen';
import { Header } from '../../src/components/layout/Header';
import { Logo } from '../../src/components/ui/Logo';
import { colors } from '../../src/constants/colors';
import { typography } from '../../src/constants/typography';
import { spacing, borderRadius } from '../../src/constants/spacing';
import { useTranslation } from '../../src/i18n/useTranslation';

export default function AboutMizanScreen() {
  const router = useRouter();
  const { t } = useTranslation();

  const [activeModal, setActiveModal] = useState<'privacy' | 'terms' | 'licenses' | null>(null);

  return (
    <SafeScreen edges={['top', 'left', 'right']}>
      <Header title={t('aboutMizan')} onBack={() => router.back()} />

      <ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
        
        {/* Brand Header */}
        <View style={styles.brandCard}>
          <Logo size={76} showText={false} style={{ marginBottom: spacing.sm }} />
          <Text style={styles.appName}>MIZAN</Text>
          <Text style={styles.appTagline}>Justice in Every Calculation</Text>
          <View style={styles.versionBadge}>
            <Text style={styles.versionText}>Version 1.0.0 (Build 100)</Text>
          </View>
        </View>

        {/* Mission Card */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Our Mission</Text>
          <Text style={styles.cardBody}>
            MIZAN is a scholar-grade Islamic Financial Assistant engineered to make classical Shariah financial calculations — Zakat and Mirath (Inheritance) — effortless, precise, and transparent.
          </Text>
          <Text style={[styles.cardBody, { marginTop: 10 }]}>
            All mathematical calculations are performed deterministically by verified Rule Engines and never generated by AI. The AI Assistant acts exclusively as an educational guide utilizing the Islamic Knowledge RAG.
          </Text>
        </View>

        {/* Shariah Governance Card */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Shariah Governance</Text>
          <Text style={styles.cardBody}>
            The Mirath rule engine enforces Quranic fixed shares (An-Nisa 4:11-12, 4:176), classical Asabah priority rules, and complete Hajb (blocking) mechanics across all recognized Madhhabs (Maliki, Hanafi, Shafi'i, Hanbali, Ja'fari).
          </Text>
        </View>

        {/* Legal Links */}
        <Text style={styles.sectionTitle}>Legal & Attributions</Text>
        <View style={styles.card}>
          <TouchableOpacity style={styles.linkRow} onPress={() => setActiveModal('privacy')}>
            <Ionicons name="shield-checkmark-outline" size={20} color={colors.secondary} />
            <Text style={styles.linkText}>Privacy Policy</Text>
            <Ionicons name="chevron-forward" size={16} color={colors.textMuted} />
          </TouchableOpacity>

          <View style={styles.divider} />

          <TouchableOpacity style={styles.linkRow} onPress={() => setActiveModal('terms')}>
            <Ionicons name="document-text-outline" size={20} color={colors.secondary} />
            <Text style={styles.linkText}>Terms & Conditions</Text>
            <Ionicons name="chevron-forward" size={16} color={colors.textMuted} />
          </TouchableOpacity>

          <View style={styles.divider} />

          <TouchableOpacity style={styles.linkRow} onPress={() => setActiveModal('licenses')}>
            <Ionicons name="code-slash-outline" size={20} color={colors.secondary} />
            <Text style={styles.linkText}>Open Source Credits & Licenses</Text>
            <Ionicons name="chevron-forward" size={16} color={colors.textMuted} />
          </TouchableOpacity>
        </View>

        <Text style={styles.copyright}>© 2026 MIZAN Platform. All Rights Reserved.</Text>

      </ScrollView>

      {/* Legal Modal */}
      <Modal
        visible={activeModal !== null}
        transparent
        animationType="slide"
        onRequestClose={() => setActiveModal(null)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContainer}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>
                {activeModal === 'privacy' && 'Privacy Policy'}
                {activeModal === 'terms' && 'Terms & Conditions'}
                {activeModal === 'licenses' && 'Open Source Credits'}
              </Text>
              <TouchableOpacity onPress={() => setActiveModal(null)}>
                <Ionicons name="close" size={24} color={colors.textSecondary} />
              </TouchableOpacity>
            </View>

            <ScrollView style={{ marginTop: 12 }}>
              {activeModal === 'privacy' && (
                <Text style={styles.legalContent}>
                  MIZAN is built with strict privacy-by-design principles. Your estate calculations, asset inputs, and financial details are processed locally on your device.

We do not sell, rent, or commercialize your personal financial data to third parties. Background sync to secure servers is encrypted and protected with industry-standard JWT authentication and TLS.
                </Text>
              )}

              {activeModal === 'terms' && (
                <Text style={styles.legalContent}>
                  MIZAN provides automated Islamic financial calculation tools and educational reference materials based on classical Shariah jurisprudence.

While our Rule Engine is thoroughly tested against classical Fiqh benchmarks, MIZAN results are for informational and planning purposes. Users should consult a qualified Mufti or licensed Islamic legal scholar for binding formal fatwas.
                </Text>
              )}

              {activeModal === 'licenses' && (
                <Text style={styles.legalContent}>
                  MIZAN relies on open source technology:

• React Native & Expo Router (MIT License)
• Zustand State Management (MIT License)
• Decimal.js (MIT License)
• Vector Icons & Google Fonts (OFL License)
                </Text>
              )}
            </ScrollView>
          </View>
        </View>
      </Modal>

    </SafeScreen>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: spacing.md,
    paddingBottom: spacing.xxl,
  },
  brandCard: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    padding: spacing.xl,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  appName: {
    fontFamily: typography.headingMedium,
    fontSize: 26,
    color: colors.white,
    letterSpacing: 2,
  },
  appTagline: {
    fontFamily: typography.body,
    fontSize: 13,
    color: colors.secondary,
    marginTop: 2,
    marginBottom: spacing.md,
  },
  versionBadge: {
    backgroundColor: colors.surfaceElevated,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  versionText: {
    fontFamily: typography.bodyBold,
    fontSize: 11,
    color: colors.textMuted,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: spacing.lg,
  },
  cardTitle: {
    fontFamily: typography.bodyBold,
    fontSize: 15,
    color: colors.white,
    marginBottom: 8,
  },
  cardBody: {
    fontFamily: typography.body,
    fontSize: 13,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  sectionTitle: {
    fontFamily: typography.bodySemiBold,
    fontSize: 13,
    color: colors.textMuted,
    marginBottom: spacing.sm,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  linkRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    gap: 12,
  },
  linkText: {
    flex: 1,
    fontFamily: typography.bodySemiBold,
    fontSize: 14,
    color: colors.white,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
  },
  copyright: {
    fontFamily: typography.body,
    fontSize: 11,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: spacing.md,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: spacing.lg,
    maxHeight: '75%',
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    fontFamily: typography.headingMedium,
    fontSize: 18,
    color: colors.white,
  },
  legalContent: {
    fontFamily: typography.body,
    fontSize: 14,
    color: colors.textSecondary,
    lineHeight: 22,
    paddingVertical: spacing.md,
  },
});
