export enum HeirType {
  HUSBAND = 'HUSBAND',
  WIFE = 'WIFE',
  SON = 'SON',
  DAUGHTER = 'DAUGHTER',
  FATHER = 'FATHER',
  MOTHER = 'MOTHER',
  PATERNAL_GRANDFATHER = 'PATERNAL_GRANDFATHER',
  MATERNAL_GRANDMOTHER = 'MATERNAL_GRANDMOTHER',
  PATERNAL_GRANDMOTHER = 'PATERNAL_GRANDMOTHER',
  FULL_BROTHER = 'FULL_BROTHER',
  FULL_SISTER = 'FULL_SISTER',
  PATERNAL_HALF_BROTHER = 'PATERNAL_HALF_BROTHER',
  PATERNAL_HALF_SISTER = 'PATERNAL_HALF_SISTER',
  MATERNAL_HALF_BROTHER = 'MATERNAL_HALF_BROTHER',
  MATERNAL_HALF_SISTER = 'MATERNAL_HALF_SISTER'
}

export interface HeirResult {
  type: HeirType;
  count: number;
  shareFraction: number;
  shareAmount: number;
  isBlocked: boolean;
  blockingReason?: string;
}
