/**
 * MIZAN — Controlled Evidence Support Categories (Phase 15)
 * Governs what specific decision aspect an evidence link supports.
 */

export const EvidenceSupportsCategory = {
  // Shared
  DEFINITION: 'DEFINITION',
  ELIGIBILITY: 'ELIGIBILITY',
  DECISION: 'DECISION',
  EXCEPTION: 'EXCEPTION',
  WARNING: 'WARNING',
  REVIEW_GATE: 'REVIEW_GATE',

  // Mirath
  FRACTION: 'FRACTION',
  RESIDUARY_STATUS: 'RESIDUARY_STATUS',
  BLOCKING: 'BLOCKING',
  PARTIAL_HIJAB_EFFECT: 'PARTIAL_HIJAB_EFFECT',
  ADJUSTMENT: 'ADJUSTMENT',
  DISTRIBUTION: 'DISTRIBUTION',

  // Zakat
  NISAB_METHOD: 'NISAB_METHOD',
  NISAB_THRESHOLD: 'NISAB_THRESHOLD',
  HOLDING_PERIOD: 'HOLDING_PERIOD',
  RATE: 'RATE',
  AGGREGATION: 'AGGREGATION',
  DEDUCTION: 'DEDUCTION',
  MONETARY_OBLIGATION: 'MONETARY_OBLIGATION',

  // Livestock
  COUNT_RANGE: 'COUNT_RANGE',
  SCHEDULE_PATTERN: 'SCHEDULE_PATTERN',
  ANIMAL_CLASS: 'ANIMAL_CLASS',
  ANIMAL_AGE: 'ANIMAL_AGE',
  ANIMAL_SEX: 'ANIMAL_SEX',
  OBLIGATION_TYPE: 'OBLIGATION_TYPE',
  ALTERNATIVE_OPTION: 'ALTERNATIVE_OPTION',

  // Agriculture
  PRODUCE_CLASSIFICATION: 'PRODUCE_CLASSIFICATION',
  MEASUREMENT_CONVERSION: 'MEASUREMENT_CONVERSION',
  HARVEST_AGGREGATION: 'HARVEST_AGGREGATION',
  IRRIGATION_CLASSIFICATION: 'IRRIGATION_CLASSIFICATION',
  MIXED_IRRIGATION_METHOD: 'MIXED_IRRIGATION_METHOD',
  AGRICULTURE_RATE: 'AGRICULTURE_RATE',
  PHYSICAL_OBLIGATION: 'PHYSICAL_OBLIGATION',
} as const;

export type EvidenceSupportsCategory =
  (typeof EvidenceSupportsCategory)[keyof typeof EvidenceSupportsCategory];

export const ALL_EVIDENCE_SUPPORTS_CATEGORIES: EvidenceSupportsCategory[] = Object.values(
  EvidenceSupportsCategory
);

export function isValidEvidenceSupportsCategory(cat: string): cat is EvidenceSupportsCategory {
  return ALL_EVIDENCE_SUPPORTS_CATEGORIES.includes(cat as EvidenceSupportsCategory);
}
