/**
 * Permanent AI Evidence Context Types Registry (Phase 16)
 */

export const AI_EVIDENCE_CONTEXT_TYPES = {
  RESULT_EVIDENCE_CONTEXT: 'RESULT_EVIDENCE_CONTEXT',
  HIJAB_EVIDENCE_CONTEXT: 'HIJAB_EVIDENCE_CONTEXT',
  MIRATH_SHARE_EVIDENCE_CONTEXT: 'MIRATH_SHARE_EVIDENCE_CONTEXT',
  MIRATH_RESIDUARY_EVIDENCE_CONTEXT: 'MIRATH_RESIDUARY_EVIDENCE_CONTEXT',
  ZAKAT_ELIGIBILITY_EVIDENCE_CONTEXT: 'ZAKAT_ELIGIBILITY_EVIDENCE_CONTEXT',
  ZAKAT_NISAB_EVIDENCE_CONTEXT: 'ZAKAT_NISAB_EVIDENCE_CONTEXT',
  ZAKAT_HAWL_EVIDENCE_CONTEXT: 'ZAKAT_HAWL_EVIDENCE_CONTEXT',
  ZAKAT_RATE_EVIDENCE_CONTEXT: 'ZAKAT_RATE_EVIDENCE_CONTEXT',
  LIVESTOCK_EVIDENCE_CONTEXT: 'LIVESTOCK_EVIDENCE_CONTEXT',
  AGRICULTURE_EVIDENCE_CONTEXT: 'AGRICULTURE_EVIDENCE_CONTEXT',
  REPORT_EVIDENCE_CONTEXT: 'REPORT_EVIDENCE_CONTEXT',
  STANDALONE_EVIDENCE_CONTEXT: 'STANDALONE_EVIDENCE_CONTEXT',
  COMPARATIVE_MADHHAB_EVIDENCE_CONTEXT: 'COMPARATIVE_MADHHAB_EVIDENCE_CONTEXT',
  REVIEW_REQUIRED_EVIDENCE_CONTEXT: 'REVIEW_REQUIRED_EVIDENCE_CONTEXT',
} as const;

export type AIEvidenceContextType = typeof AI_EVIDENCE_CONTEXT_TYPES[keyof typeof AI_EVIDENCE_CONTEXT_TYPES];

export const ALL_AI_EVIDENCE_CONTEXT_TYPES: AIEvidenceContextType[] = Object.values(AI_EVIDENCE_CONTEXT_TYPES);

export function isValidAIEvidenceContextType(type: string): type is AIEvidenceContextType {
  return ALL_AI_EVIDENCE_CONTEXT_TYPES.includes(type as AIEvidenceContextType);
}
