/**
 * AI Evidence Retrieval Mode Registry (Phase 16)
 */

export const AI_EVIDENCE_RETRIEVAL_MODES = {
  NO_ADDITIONAL_RETRIEVAL: 'NO_ADDITIONAL_RETRIEVAL',
  RELATED_APPROVED_EXPLANATIONS: 'RELATED_APPROVED_EXPLANATIONS',
  RELATED_APPROVED_TERMINOLOGY: 'RELATED_APPROVED_TERMINOLOGY',
  RELATED_APPROVED_EVIDENCE: 'RELATED_APPROVED_EVIDENCE',
  APP_GUIDE_ONLY: 'APP_GUIDE_ONLY',
  APPROVED_COMPARATIVE_RECORD_ONLY: 'APPROVED_COMPARATIVE_RECORD_ONLY',
} as const;

export type AIEvidenceRetrievalMode = typeof AI_EVIDENCE_RETRIEVAL_MODES[keyof typeof AI_EVIDENCE_RETRIEVAL_MODES];

export const ALL_AI_EVIDENCE_RETRIEVAL_MODES: AIEvidenceRetrievalMode[] = Object.values(AI_EVIDENCE_RETRIEVAL_MODES);
