/**
 * AI Evidence Context Completeness Registry (Phase 16)
 */

export const AI_EVIDENCE_CONTEXT_COMPLETENESS = {
  FULLY_VERIFIED: 'FULLY_VERIFIED',
  VERIFIED_WITH_APPROVED_FALLBACK: 'VERIFIED_WITH_APPROVED_FALLBACK',
  PARTIALLY_VERIFIED_FOR_DISPLAY: 'PARTIALLY_VERIFIED_FOR_DISPLAY',
  INSUFFICIENT_VERIFIED_CONTEXT: 'INSUFFICIENT_VERIFIED_CONTEXT',
  INTEGRITY_FAILURE: 'INTEGRITY_FAILURE',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export type AIEvidenceContextCompletenessStatus = typeof AI_EVIDENCE_CONTEXT_COMPLETENESS[keyof typeof AI_EVIDENCE_CONTEXT_COMPLETENESS];

export const ALL_AI_EVIDENCE_CONTEXT_COMPLETENESS: AIEvidenceContextCompletenessStatus[] = Object.values(AI_EVIDENCE_CONTEXT_COMPLETENESS);
