/**
 * Explanation Variable Definitions Registry
 * Phase 11 — MIZAN Multilingual Explanation and Localization System
 */

import { ExplanationVariableDefinition, ExplanationVariableId } from '../types/explanation/explanation-variable.types';

export const EXPLANATION_VARIABLE_DEFINITIONS: Record<ExplanationVariableId, ExplanationVariableDefinition> = {
  HEIR_NAME: {
    variableId: 'HEIR_NAME',
    valueType: 'ENTITY_LABEL',
    sourcePath: 'heirId',
    required: true,
    formattingPolicyId: 'ENTITY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'FAIL_RENDERING',
    description: 'Name of the heir in the resolved language',
  },
  BLOCKED_HEIR_NAME: {
    variableId: 'BLOCKED_HEIR_NAME',
    valueType: 'ENTITY_LABEL',
    sourcePath: 'blockedHeirId',
    required: false,
    formattingPolicyId: 'ENTITY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Name of the heir who was blocked',
  },
  BLOCKER_HEIR_NAME: {
    variableId: 'BLOCKER_HEIR_NAME',
    valueType: 'ENTITY_LABEL',
    sourcePath: 'blockerHeirId',
    required: false,
    formattingPolicyId: 'ENTITY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Name of the heir who caused the blocking',
  },
  ZAKAT_CATEGORY_NAME: {
    variableId: 'ZAKAT_CATEGORY_NAME',
    valueType: 'CATEGORY_LABEL',
    sourcePath: 'categoryId',
    required: true,
    formattingPolicyId: 'CATEGORY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'FAIL_RENDERING',
    description: 'Zakat asset category label',
  },
  PRODUCE_TYPE_NAME: {
    variableId: 'PRODUCE_TYPE_NAME',
    valueType: 'CATEGORY_LABEL',
    sourcePath: 'produceTypeId',
    required: false,
    formattingPolicyId: 'CATEGORY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Agricultural produce type label',
  },
  ANIMAL_TYPE_NAME: {
    variableId: 'ANIMAL_TYPE_NAME',
    valueType: 'CATEGORY_LABEL',
    sourcePath: 'animalTypeId',
    required: false,
    formattingPolicyId: 'CATEGORY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Livestock animal type label',
  },
  SHARE_FRACTION: {
    variableId: 'SHARE_FRACTION',
    valueType: 'FRACTION',
    sourcePath: 'share',
    required: true,
    formattingPolicyId: 'FRACTION-DISPLAY-STANDARD-001',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'FAIL_RENDERING',
    description: 'Exact Mirath share fraction { numerator, denominator }',
  },
  SHARE_PERCENTAGE: {
    variableId: 'SHARE_PERCENTAGE',
    valueType: 'DECIMAL',
    sourcePath: 'sharePercentage',
    required: false,
    formattingPolicyId: 'DECIMAL-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Supplementary percentage representation of a share',
  },
  MONETARY_AMOUNT: {
    variableId: 'MONETARY_AMOUNT',
    valueType: 'MONEY',
    sourcePath: 'monetaryValue',
    required: false,
    formattingPolicyId: 'MONEY-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Calculated monetary value in captured currency',
  },
  CURRENCY_CODE: {
    variableId: 'CURRENCY_CODE',
    valueType: 'TEXT',
    sourcePath: 'currencyCode',
    required: false,
    formattingPolicyId: 'TEXT-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Captured currency code ISO 4217',
  },
  NISAB_AMOUNT: {
    variableId: 'NISAB_AMOUNT',
    valueType: 'MONEY',
    sourcePath: 'nisabThreshold',
    required: false,
    formattingPolicyId: 'MONEY-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Resolved Nisab threshold amount',
  },
  HARVEST_QUANTITY: {
    variableId: 'HARVEST_QUANTITY',
    valueType: 'DECIMAL',
    sourcePath: 'harvestQuantity',
    required: false,
    formattingPolicyId: 'DECIMAL-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Total agricultural harvest quantity',
  },
  LIVESTOCK_COUNT: {
    variableId: 'LIVESTOCK_COUNT',
    valueType: 'INTEGER',
    sourcePath: 'animalCount',
    required: false,
    formattingPolicyId: 'INTEGER-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Livestock animal count',
  },
  SELECTED_MADHHAB: {
    variableId: 'SELECTED_MADHHAB',
    valueType: 'ENTITY_LABEL',
    sourcePath: 'selectedMadhhab',
    required: true,
    formattingPolicyId: 'ENTITY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'FAIL_RENDERING',
    description: 'Selected Madhhab name',
  },
  EVIDENCE_REFERENCE: {
    variableId: 'EVIDENCE_REFERENCE',
    valueType: 'EVIDENCE_REFERENCE',
    sourcePath: 'evidenceCitation',
    required: false,
    formattingPolicyId: 'EVIDENCE-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Formatted evidence reference citation',
  },
  CALCULATION_DATE: {
    variableId: 'CALCULATION_DATE',
    valueType: 'DATE',
    sourcePath: 'calculatedAt',
    required: false,
    formattingPolicyId: 'DATE-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Calculation timestamp',
  },
  IRRIGATION_METHOD_NAME: {
    variableId: 'IRRIGATION_METHOD_NAME',
    valueType: 'CATEGORY_LABEL',
    sourcePath: 'irrigationMethod',
    required: false,
    formattingPolicyId: 'CATEGORY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Agriculture irrigation classification',
  },
  RATE_FRACTION: {
    variableId: 'RATE_FRACTION',
    valueType: 'FRACTION',
    sourcePath: 'rateFraction',
    required: false,
    formattingPolicyId: 'FRACTION-DISPLAY-STANDARD-001',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Zakat rate exact fraction (e.g. 1/40, 1/10, 1/20)',
  },
  OBLIGATION_QUANTITY: {
    variableId: 'OBLIGATION_QUANTITY',
    valueType: 'DECIMAL',
    sourcePath: 'obligationQuantity',
    required: false,
    formattingPolicyId: 'DECIMAL-DISPLAY-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Physical obligation weight/volume/count',
  },
  UNIT_NAME: {
    variableId: 'UNIT_NAME',
    valueType: 'CATEGORY_LABEL',
    sourcePath: 'unitId',
    required: false,
    formattingPolicyId: 'CATEGORY-LABEL-STANDARD',
    allowedSources: ['STRUCTURED_CALCULATION_RESULT'],
    fallbackBehaviour: 'OMIT',
    description: 'Measurement unit label (e.g. Wasq, Kg)',
  },
};
